### PR TITLE
Compare fw versions and links to download

### PR DESCRIPTION
**Pull request by Flobul**
Check online firmware version, compare and add link to download.
Capture d’écran 2024-01-07 à 10 54 42

### CODE REVIEW

**Comment by Domochip** [comment]
Thanks a lot for this nice idea! It should be ported to WirelessBase.
It just popped in my mind that i have something similar on my Wifi AP : 
image
It is interesting to have a button to trigger the verification or at least consider that Internet is not available during the first boot experience (or access blocked).

**Comment by Flobul** [comment]
Thanks.
This is what I had in my mind.
But I don't think it's possible to make OTA in JS (client side)
Github blocks 302 redirect.

So far, here is what I've made. (OTA button is not working)
Capture d’écran 2024-01-13 à 12 42 28
Capture d’écran 2024-01-13 à 12 42 37

**Comment by Flobul** [comment]
Here you go, with OTA up and running.

**Comment by Domochip** [comment]
Hello,

I'm really sorry but next to Home Assistant integration, I changed my mind and implemented it in a very different way.
The "backend" code is looking for lastest version available on github and not the frontend.
I'm doing it this way because then, I can push this lastest version infos to Home Assistant via MQTT.
it is then possible to trigger a module "Online Update" from the firmware page but also via MQTT (Directly from Home Assistant)

**Comment by Domochip** [comment]
I've also simplified naming and versioning

**Comment by Flobul** [comment]
> Hello,
> 
> I'm really sorry but next to Home Assistant integration, I changed my mind and implemented it in a very different way. The "backend" code is looking for lastest version available on github and not the frontend. I'm doing it this way because then, I can push this lastest version infos to Home Assistant via MQTT. it is then possible to trigger a module "Online Update" from the firmware page but also via MQTT (Directly from Home Assistant)

It' even better that way, nicely done.
Haven't tested yet.

**Comment by Domochip** [comment]
Closing because new version released

**Pull request closed without merging**
