### PR TITLE
Improve Home Assistant tempertaure entities for Hydro stove

### PR DESCRIPTION
**Pull request by tanc**
This add `SPLMIN` and `SPLMAX` as variables which are used as the min and max available for the SetPoint if available, otherwise falling back to the hard coded values.

Adds a new boolean `isFluidType` based off the stove value `FLUID`.

It adds a new Water Temperature entity and wraps Room Temperature in a condition so that one or the other is used depending on the boolean `isFluidType`

I've never coded in C++ and I haven't tested this so let me know if something isn't right. It does compile though.

Ref #58

### CODE REVIEW

**Comment by tanc** [comment]
ok, I bit the bullet and uploaded the firmware. I can confirm this fixes my issue with the setpoint and I can also see the new Stove Water Temperature entity.

image

**Comment by Domochip** [comment]
thanks for your PR, I was about to do it.
I'll improve it in the coming days and then merge it

**Comment by tanc** [comment]
Awesome, thanks! I couldn't resist tinkering with it, one of the joys of open source

**Comment by Domochip** [comment]
😆

**Comment by Domochip** [comment]
Hi,

I'll need your help to understand some italian names.
Could you confirm my translations:
- kTemperaturaAmbiente: Temp. Ambiente => Room temperature
- kTemperaturaAccumulo: Temp. Accumulo => Water tank temperature OR Storage water temperature
- kTemperaturaAcquaRitorno: Temp. Ritorno => Return water temperature
- kTemperaturaAcquaMandata: Temp. Mandata => Supply water temperature

Regarding 2nd one, does Accumulo correspond to a tank to buffer hot water?
Which translation looks better for you?

thanks

**Comment by Domochip** [comment]
Finally found some text in Android App:
kTemperaturaAccumulo: TANK
kTemperaturaAcquaMandata: FLOW
kTemperaturaAcquaRitorno: RETURN
kTemperaturaAmbiente: AMBIENT

**Comment by tanc** [comment]
These translations make sense to me:

kTemperaturaAmbiente: Temp. Ambiente => Room temperature
kTemperaturaAccumulo: Temp. Accumulo => Water tank temperature
kTemperaturaAcquaRitorno: Temp. Ritorno => Return water temperature
kTemperaturaAcquaMandata: Temp. Mandata => Outgoing water temperature

Accumulo is usually a buffer tank but in this case its the inbuilt water tank in the stove, so "water tank temperature" makes sense.

**Comment by Domochip** [comment]
I'll need more infos from your STDT.
Could you give it to me without the serial number, please

**Comment by tanc** [comment]
I've removed identifying info:
```
{
    "INFO": {
        "CMD": "GET STDT",
        "RSP": "OK"
    },
    "DATA": {
        "LABEL": "palacontrol",
        "GWDEVICE": "wlan0",
        "MAC": "-",
        "GATEWAY": "-",
        "DNS": [
            "-"
        ],
        "WMAC": "-",
        "WMODE": "sta",
        "WADR": "6",
        "WGW": "-",
        "WENC": "psk2",
        "WPWR": "-83 dBm",
        "WSSID": "-",
        "WPR": "dhcp",
        "WMSK": "-",
        "WBCST": "-",
        "WCH": "9",
        "EPR": "dhcp",
        "EGW": "0.0.0.0",
        "EMSK": "0.0.0.0",
        "EADR": "0.0.0.0",
        "EMAC": "-",
        "ECBL": "down",
        "EBCST": "",
        "APLCONN": 1,
        "ICONN": 0,
        "CBTYPE": "miniembplug",
        "sendmsg": "2.1.2 2018-03-28 10:19:09",
        "plzbridge": "2.2.1 2022-10-24 11:13:21",
        "SYSTEM": "2.5.3 2021-10-08 10:30:20 (657c8cf)",
        "CLOUD_ENABLED": true,
        "SN": "-",
        "SNCHK": 1,
        "MBTYPE": 0,
        "MOD": 83,
        "VER": 47,
        "CORE": 137,
        "FWDATE": "2023-01-30",
        "FLUID": 1,
        "SPLMIN": 65,
        "SPLMAX": 80,
        "UICONFIG": 1,
        "HWTYPE": 6,
        "DSPTYPE": 1,
        "DSPFWVER": 31,
        "CONFIG": 1,
        "PELLETTYPE": 2,
        "PSENSTYPE": 0,
        "PSENSLMAX": 0,
        "PSENSLTSH": 0,
        "PSENSLMIN": 0,
        "MAINTPROBE": 0,
        "STOVETYPE": 2,
        "FAN2TYPE": 1,
        "FAN2MODE": 1,
        "BLEMBMODE": 7,
        "BLEDSPMODE": 1,
        "CHRONOTYPE": 0,
        "AUTONOMYTYPE": 1,
        "NOMINALPWR": 16
    },
    "SUCCESS": true
}
```

**Comment by Domochip** [comment]
Thanks a lot.
I found out this 2 documentation : 
https://chemineeo.fr/media/pdf/f9/95/d0/Benutzerhandbuch-und-Datenblatt-Pelletofen-Palazzetti-Ginger-Idro-12.pdf
https://cdn.palazzetti.it/manuals/004773820.pdf

I got that you are in Configuration 1.
Could you let me know what temperature is measured by T01,T02,T04 and T05?

**Comment by tanc** [comment]
Do you know where I would find the info you need for T1,T2,T4 and T5?

**Comment by Domochip** [comment]
Yes, you can go to this address:
[wpalacontrol.local/](http://wpalacontrol.local/cgi-bin/sendmsg.lua?cmd=GET+TMPS)http://[wpalacontrol.local/cgi-bin/sendmsg.lua?cmd=GET+TMPS](http://wpalacontrol.local/cgi-bin/sendmsg.lua?cmd=GET+TMPS)

**Comment by tanc** [comment]
My guess for these would be:

T1 Outgoing water temp
T2 Return water temp
T3 Firebox/combustion air temp
T5 Room temp

**Comment by Domochip** [comment]
OK, last commits should be better regarding sensors.
The logic is not well described by Palazzetti/Fumis but it should now do the trick
In your case, it should create 2 sensors : 
- Supply Water : water coming out of your stove
- Return Water: coming back

In your current configuration Room temperature is not considered so I don't create the sensor.

Could you give it a try

**Comment by Domochip** [comment]
Sorry, I then have another question for you
I can see this in the documentation
image
It says the stove will modulate output when reaching the set point.
But in your case, It starts to modulate when the temperature is reached for Supply Water or Return Water?

**Comment by tanc** [comment]
I was also curious about this so I made this video observing the data for 15 minutes, which is a full heating/cooling cycle with today's temps. I've sped up the video 12x so its not so long.

In the video I have the setpoint at 69 degrees. It looks like T1 is the water tank (or outgoing temp).

The video starts with the setpoint achieved (exceeded) and you can see the firebox temperature is lowering. With the flame low the water temperature starts to lower slowly. Once it lowers too far the fan increases in speed (not shown in video, I was listening) which increases the fuel burning rate and you can see in the video the firebox temp increases until the T1 again reaches the setpoint.

It appears it tries to maintain the setpoint for a while and the setpoint temperature is exceeded by about a degree. Then it lowers the fan speed which reduces the burning temperature. It doesn't let the water temperature drop too far before applying heat again.

This is in 'power level' 3 of 5. With higher power levels it burns more fuel but probably maintains the set point for longer and/or doesn't let the water temperature drop too far.

https://github.com/user-attachments/assets/c6c183ee-db4c-4b69-8ffb-de3816b1c946

**Comment by Domochip** [comment]
Ok, thanks again for your help.
That means the setpoint is to control the Supply Water (outgoing) temperature which is logic in the end.
So for you the "Main" temperature (which match Setpoint) is T1

I'll merge the code of this PR.
Again, thanks for your help, It helps to clarify some points as I Have an Air type stove ;-)

**Comment by tanc** [comment]
Awesome! Thanks so much

**Pull request merged**
